# Site settings
title: Freelancer
email: kandi4joy@gmail.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Architect - Graphic Artist - Landscape Designer"
meta_author: Yana Joy

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 637D98 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 66cdaa #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: yanajoy.github.io
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: facebook
    url: https://www.facebook.com/yana.joy.524



# Postal address (add as many lines as necessary)
address:
  - line: Nha Trang, Vietnam

# Credits content
credits: 'Created using <a href="https://jekyllrb.com">Jekyll</a> <br> with <a href="http://github.com/jeromelachaud/freelancer-theme">Freelancer</a> theme.'

# Build settings
markdown: kramdown
permalink: none

collections:
  country_houses:
    title : Country Houses
    output: true
  landscape_design:
    title : Landscape design
    output: true
  interiors:
    title : Interiors
    output: true
  public_architecture:
    title : Public architecture
    output: true
